### PR TITLE
fixes criminals not being recognized as evil

### LINKED ISSUE #95: [bug] ravendark doors not opening for evil characters
Playing on my wanted character (which is always red), whenever I try to enter a ravendark building I get this message:
image

At this time, the character is at -8k karma:
image

The code that checks for it is here: 
image

Furthermore, npcs inside the houses seem to be hostile to me. They are evil people, in the evil city. I dont think that this is how this is supposed to work.

### PR DESCRIPTION
**Pull request by EstelMatiazi**
Fixes #95

### CODE REVIEW

**Comment by creiht** [comment]
I'm worried about other side effects this change might have...  Looking through the code, it does seem to be the intent that a fugitive is not evil by default in the game.  The narrative also seems to support this.  There's also a quest that reverts their fugitive status, which could put them back in good standing.

**Comment by creiht** [comment]
Another way to think of it, looking at the EvilPlayer() method, it feels like the intent is more about the path the player has chosen (as a Death Knight, or Syth, etc.)  Other murderers aren't considered evil in this case.  Now if someone that was a criminal were to chose one of these paths, then they would have access.

**Comment by creiht** [comment]
Maybe a compromise is if the character is a fugitive and has a certain amount of negative karma, then they have access?  (rather than just being a fugitive)

**Comment by EstelMatiazi** [comment]
> I'm worried about other side effects this change might have... Looking through the code, it does seem to be the intent that a fugitive is not evil by default in the game. The narrative also seems to support this. There's also a quest that reverts their fugitive status, which could put them back in good standing.

When you start a fugitive, ravendark is marked as one of your safe spots in the game, regardless of karma or how 'evil' you are.

**Review by mz1193 — APPROVED** [review]
Looks good Estel. I understand creiht's thoughts on this, but yes, Ravendark is on the approved list as seen here:

image

I find it very unlikely that the original intent was for criminals to be blocked from Ravendark given that information.

I do, however, like the suggestion of a possible low karma requirement to access this particular city. But I feel like that needs more discussion in the future. For now, I personally think this fix is good to go as-is.

**Comment by sosarian-scribe** [comment]
Having looked some more at the code, I think it is intentional.
Fugitives/murderers/criminals can enter if they do dark arts type of evil: Necromancy, undertaking, death knights, syths, and undead players.
So, I don't think #95 is a bug. You have access if you do dark arts. We could consider if we should somehow describe that better somewhere in books or in that list.

**Comment by mz1193** [comment]
An idea that was brought up in discussion of this earlier would be to tie access to Ravendark to the possession of a key that would drop from Dracula as an alternative to the low karma requirement. While I personally think that Ravendark should just be open to reds as this PR intends to do, I also think the "Dracula key bypass" idea is neat. Would you consider this an equitable solution @EstelMatiazi ?

**Comment by EstelMatiazi** [comment]
> An idea that was brought up in discussion of this earlier would be to tie access to Ravendark to the possession of a key that would drop from Dracula as an alternative to the low karma requirement. While I personally think that Ravendark should just be open to reds as this PR intends to do, I also think the "Dracula key bypass" idea is neat. Would you consider this an equitable solution @EstelMatiazi ?

No, not at all. If I am some sort of evil mastermind I might have zero interest in killing another evil mastermind to gain the privilege of entering a bakery or jewelry store or whatever. This makes no sense.

**Comment by mz1193** [comment]
> > An idea that was brought up in discussion of this earlier would be to tie access to Ravendark to the possession of a key that would drop from Dracula as an alternative to the low karma requirement. While I personally think that Ravendark should just be open to reds as this PR intends to do, I also think the "Dracula key bypass" idea is neat. Would you consider this an equitable solution @EstelMatiazi ?
> 
> No, not at all. If I am some sort of evil mastermind I might have zero interest in killing another evil mastermind to gain the privilege of entering a bakery or jewelry store or whatever. This makes no sense.

I understand. It does make little sense for a murderer to specifically hunt down Dracula for this purpose.

**Comment by sosarian-scribe** [comment]
Okay okay - I am warming up to merging this change since it is listed as cities fugitives can access and the change doesn't allow any arbitrary criminal to open the doors.

**Comment by mz1193** [comment]
> Okay okay - I am warming up to merging this change since it is listed as cities fugitives can access and the change doesn't allow any arbitrary criminal to open the doors.



> If we do decide to do it, honestly I would vote to just open it up to make it available to all players.

I'm on board with this. I know the solution won't please everyone at the moment, but in the future we can still work toward ways to improve the area that may be liked by all.

I still think the "Dracula key bypass" idea is interesting, but maybe a similar solution can be found at some point that doesn't involve murderers specifically targetting an arguably bigger murderer in old Drac, haha.

**Pull request merged**
